[programs.localnet]
time_locked_fund = "EJReuMV3KRJVJBSQPhU1aTr5SZWUQfRXc14hiFY2gBoc"

[programs.devnet]
time_locked_fund = "EJReuMV3KRJVJBSQPhU1aTr5SZWUQfRXc14hiFY2gBoc"

[programs.mainnet]
time_locked_fund = "EJReuMV3KRJVJBSQPhU1aTr5SZWUQfRXc14hiFY2gBoc"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
